services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - '3306:3306'
    volumes:
      - bun-api-mysql-data:/var/lib/mysql
    restart: always

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - bun-api-redis-data:/data
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - '5173:5173'

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - '8090:8090'
    depends_on:
      - mysql
      - redis

volumes:
  bun-api-mysql-data:
  bun-api-redis-data:
